version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: muhammadabdumalik/podarki-uz-backend:latest
    ports:
      - "3001:3001"
